#
# author: Michael Brockus.
# gmail: mailto:michaelbrockus@gmail.com
#
FROM debian:bullseye

ENV DEBIAN_FRONTEND noninteractive
ENV LANG 'C.UTF-8'
ENV CI 1

RUN apt-get update --fix-missing && apt-get upgrade -y \
    && apt-get -y install \
       apt-utils \
       pkg-config \
       git \
       rustc \
       libssl-dev \
    && rm -rf /var/lib/apt/lists/*
